services:
  mongo:
    image: mongo:8.0.3-noble
    restart: on-failure
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - task-nexus-network
    volumes:
      - task-nexus-mongo-vol-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

  minio:
    image: minio/minio:latest
    ports:
      - ${MINIO_API_PORT}:9000  # API Port
      - ${MINIO_WEB_UI_PORT}:9001  # Web UI Port
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":${MINIO_WEB_UI_PORT}"
    networks:
      - task-nexus-network
    restart: on-failure
    volumes:
      - task-nexus-minio-vol:/data

  redis:
    image: redis:7.4.2-alpine
    restart: on-failure
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - task-nexus-network
    volumes:
      - task-nexus-redis-vol:/data
      - task-nexus-redis-config-vol:/usr/local/etc/redis
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}

volumes:
  task-nexus-mongo-vol-db:
    driver: local
  task-nexus-redis-vol:
    driver: local
  task-nexus-redis-config-vol:
    driver: local
  task-nexus-minio-vol:
    driver: local

networks:
  task-nexus-network:
    driver: bridge
